-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: GameConfig

local flatbuffers = require('3rd.flatbuffers')

local GamePlayList = {} -- the module
local GamePlayList_mt = {} -- the class metatable

function GamePlayList.New()
    local o = {}
    setmetatable(o, {__index = GamePlayList_mt})
    return o
end
function GamePlayList.GetRootAsGamePlayList(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = GamePlayList.New()
    o:Init(buf, n + offset)
    return o
end
function GamePlayList_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function GamePlayList_mt:Data(j)
    local o = self.view:Offset(4)
    if o ~= 0 then
        local x = self.view:Vector(o)
        x = x + ((j-1) * 4)
        x = self.view:Indirect(x)
        local obj = require('GameConfig.GamePlay').New()
        obj:Init(self.view.bytes, x)
        return obj
    end
end
function GamePlayList_mt:DataLength()
    local o = self.view:Offset(4)
    if o ~= 0 then
        return self.view:VectorLen(o)
    end
    return 0
end
function GamePlayList.Start(builder) builder:StartObject(1) end
function GamePlayList.AddData(builder, data) builder:PrependUOffsetTRelativeSlot(0, data, 0) end
function GamePlayList.StartDataVector(builder, numElems) return builder:StartVector(4, numElems, 4) end
function GamePlayList.End(builder) return builder:EndObject() end

return GamePlayList -- return the module