-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: GameConfig

local flatbuffers = require('3rd.flatbuffers')

local Scene = {} -- the module
local Scene_mt = {} -- the class metatable

function Scene.New()
    local o = {}
    setmetatable(o, {__index = Scene_mt})
    return o
end
function Scene.GetRootAsScene(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = Scene.New()
    o:Init(buf, n + offset)
    return o
end
function Scene_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function Scene_mt:Id()
    local o = self.view:Offset(4)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Uint32, o + self.view.pos)
    end
    return 0
end
function Scene_mt:AssetName()
    local o = self.view:Offset(6)
    if o ~= 0 then
        return self.view:String(o + self.view.pos)
    end
end
function Scene_mt:MapConfig()
    local o = self.view:Offset(8)
    if o ~= 0 then
        return self.view:String(o + self.view.pos)
    end
end
function Scene.Start(builder) builder:StartObject(3) end
function Scene.AddId(builder, Id) builder:PrependUint32Slot(0, Id, 0) end
function Scene.AddAssetName(builder, AssetName) builder:PrependUOffsetTRelativeSlot(1, AssetName, 0) end
function Scene.AddMapConfig(builder, MapConfig) builder:PrependUOffsetTRelativeSlot(2, MapConfig, 0) end
function Scene.End(builder) return builder:EndObject() end

return Scene -- return the module