-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: GameConfig

local flatbuffers = require('3rd.flatbuffers')

local SoundList = {} -- the module
local SoundList_mt = {} -- the class metatable

function SoundList.New()
    local o = {}
    setmetatable(o, {__index = SoundList_mt})
    return o
end
function SoundList.GetRootAsSoundList(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = SoundList.New()
    o:Init(buf, n + offset)
    return o
end
function SoundList_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function SoundList_mt:Data(j)
    local o = self.view:Offset(4)
    if o ~= 0 then
        local x = self.view:Vector(o)
        x = x + ((j-1) * 4)
        x = self.view:Indirect(x)
        local obj = require('GameConfig.Sound').New()
        obj:Init(self.view.bytes, x)
        return obj
    end
end
function SoundList_mt:DataLength()
    local o = self.view:Offset(4)
    if o ~= 0 then
        return self.view:VectorLen(o)
    end
    return 0
end
function SoundList.Start(builder) builder:StartObject(1) end
function SoundList.AddData(builder, data) builder:PrependUOffsetTRelativeSlot(0, data, 0) end
function SoundList.StartDataVector(builder, numElems) return builder:StartVector(4, numElems, 4) end
function SoundList.End(builder) return builder:EndObject() end

return SoundList -- return the module
