-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: GameConfig

local flatbuffers = require('3rd.flatbuffers')

local Sound = {} -- the module
local Sound_mt = {} -- the class metatable

function Sound.New()
    local o = {}
    setmetatable(o, {__index = Sound_mt})
    return o
end
function Sound.GetRootAsSound(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = Sound.New()
    o:Init(buf, n + offset)
    return o
end
function Sound_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function Sound_mt:Id()
    local o = self.view:Offset(4)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Uint32, o + self.view.pos)
    end
    return 0
end
function Sound_mt:GroupName()
    local o = self.view:Offset(6)
    if o ~= 0 then
        return self.view:String(o + self.view.pos)
    end
end
function Sound_mt:Loop()
    local o = self.view:Offset(8)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Uint32, o + self.view.pos)
    end
    return 0
end
function Sound_mt:Volume()
    local o = self.view:Offset(10)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Float32, o + self.view.pos)
    end
    return 0.0
end
function Sound_mt:AssetPath()
    local o = self.view:Offset(12)
    if o ~= 0 then
        return self.view:String(o + self.view.pos)
    end
end
function Sound.Start(builder) builder:StartObject(5) end
function Sound.AddId(builder, Id) builder:PrependUint32Slot(0, Id, 0) end
function Sound.AddGroupName(builder, GroupName) builder:PrependUOffsetTRelativeSlot(1, GroupName, 0) end
function Sound.AddLoop(builder, Loop) builder:PrependUint32Slot(2, Loop, 0) end
function Sound.AddVolume(builder, Volume) builder:PrependFloat32Slot(3, Volume, 0.0) end
function Sound.AddAssetPath(builder, AssetPath) builder:PrependUOffsetTRelativeSlot(4, AssetPath, 0) end
function Sound.End(builder) return builder:EndObject() end

return Sound -- return the module