-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: GameConfig

local flatbuffers = require('3rd.flatbuffers')

local UIWindowList = {} -- the module
local UIWindowList_mt = {} -- the class metatable

function UIWindowList.New()
    local o = {}
    setmetatable(o, {__index = UIWindowList_mt})
    return o
end
function UIWindowList.GetRootAsUIWindowList(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = UIWindowList.New()
    o:Init(buf, n + offset)
    return o
end
function UIWindowList_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function UIWindowList_mt:Data(j)
    local o = self.view:Offset(4)
    if o ~= 0 then
        local x = self.view:Vector(o)
        x = x + ((j-1) * 4)
        x = self.view:Indirect(x)
        local obj = require('GameConfig.UIWindow').New()
        obj:Init(self.view.bytes, x)
        return obj
    end
end
function UIWindowList_mt:DataLength()
    local o = self.view:Offset(4)
    if o ~= 0 then
        return self.view:VectorLen(o)
    end
    return 0
end
function UIWindowList.Start(builder) builder:StartObject(1) end
function UIWindowList.AddData(builder, data) builder:PrependUOffsetTRelativeSlot(0, data, 0) end
function UIWindowList.StartDataVector(builder, numElems) return builder:StartVector(4, numElems, 4) end
function UIWindowList.End(builder) return builder:EndObject() end

return UIWindowList -- return the module
