-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: GameConfig

local flatbuffers = require('3rd.flatbuffers')

local Sound = {} -- the module
local Sound_mt = {} -- the class metatable

function Sound.New()
    local o = {}
    setmetatable(o, {__index = Sound_mt})
    return o
end
function Sound.GetRootAsSound(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = Sound.New()
    o:Init(buf, n + offset)
    return o
end
function Sound_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function Sound_mt:Id()
    local o = self.view:Offset(4)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Uint32, o + self.view.pos)
    end
    return 0
end
function Sound_mt:SoundName()
    local o = self.view:Offset(6)
    if o ~= 0 then
        return self.view:String(o + self.view.pos)
    end
end
function Sound_mt:SoundGroupName()
    local o = self.view:Offset(8)
    if o ~= 0 then
        return self.view:String(o + self.view.pos)
    end
end
function Sound_mt:SoundPriority()
    local o = self.view:Offset(10)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Uint32, o + self.view.pos)
    end
    return 0
end
function Sound_mt:Loop()
    local o = self.view:Offset(12)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Uint32, o + self.view.pos)
    end
    return 0
end
function Sound_mt:SoundVolume()
    local o = self.view:Offset(14)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Float32, o + self.view.pos)
    end
    return 0.0
end
function Sound_mt:AssetPath()
    local o = self.view:Offset(16)
    if o ~= 0 then
        return self.view:String(o + self.view.pos)
    end
end
function Sound.Start(builder) builder:StartObject(7) end
function Sound.AddId(builder, Id) builder:PrependUint32Slot(0, Id, 0) end
function Sound.AddSoundName(builder, SoundName) builder:PrependUOffsetTRelativeSlot(1, SoundName, 0) end
function Sound.AddSoundGroupName(builder, SoundGroupName) builder:PrependUOffsetTRelativeSlot(2, SoundGroupName, 0) end
function Sound.AddSoundPriority(builder, SoundPriority) builder:PrependUint32Slot(3, SoundPriority, 0) end
function Sound.AddLoop(builder, Loop) builder:PrependUint32Slot(4, Loop, 0) end
function Sound.AddSoundVolume(builder, SoundVolume) builder:PrependFloat32Slot(5, SoundVolume, 0.0) end
function Sound.AddAssetPath(builder, AssetPath) builder:PrependUOffsetTRelativeSlot(6, AssetPath, 0) end
function Sound.End(builder) return builder:EndObject() end

return Sound -- return the module