-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: GameConfig

local flatbuffers = require('3rd.flatbuffers')

local Vocation = {} -- the module
local Vocation_mt = {} -- the class metatable

function Vocation.New()
    local o = {}
    setmetatable(o, {__index = Vocation_mt})
    return o
end
function Vocation.GetRootAsVocation(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = Vocation.New()
    o:Init(buf, n + offset)
    return o
end
function Vocation_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function Vocation_mt:Id()
    local o = self.view:Offset(4)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Uint32, o + self.view.pos)
    end
    return 0
end
function Vocation_mt:MaxHealth()
    local o = self.view:Offset(6)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Float32, o + self.view.pos)
    end
    return 0.0
end
function Vocation_mt:MoveSpeed()
    local o = self.view:Offset(8)
    if o ~= 0 then
        return self.view:Get(flatbuffers.N.Float32, o + self.view.pos)
    end
    return 0.0
end
function Vocation.Start(builder) builder:StartObject(3) end
function Vocation.AddId(builder, Id) builder:PrependUint32Slot(0, Id, 0) end
function Vocation.AddMaxHealth(builder, MaxHealth) builder:PrependFloat32Slot(1, MaxHealth, 0.0) end
function Vocation.AddMoveSpeed(builder, MoveSpeed) builder:PrependFloat32Slot(2, MoveSpeed, 0.0) end
function Vocation.End(builder) return builder:EndObject() end

return Vocation -- return the module