-- automatically generated by the FlatBuffers compiler, do not modify

-- namespace: GameConfig

local flatbuffers = require('3rd.flatbuffers')

local VocationList = {} -- the module
local VocationList_mt = {} -- the class metatable

function VocationList.New()
    local o = {}
    setmetatable(o, {__index = VocationList_mt})
    return o
end
function VocationList.GetRootAsVocationList(buf, offset)
    local n = flatbuffers.N.UOffsetT:Unpack(buf, offset)
    local o = VocationList.New()
    o:Init(buf, n + offset)
    return o
end
function VocationList_mt:Init(buf, pos)
    self.view = flatbuffers.view.New(buf, pos)
end
function VocationList_mt:Data(j)
    local o = self.view:Offset(4)
    if o ~= 0 then
        local x = self.view:Vector(o)
        x = x + ((j-1) * 4)
        x = self.view:Indirect(x)
        local obj = require('GameConfig.Vocation').New()
        obj:Init(self.view.bytes, x)
        return obj
    end
end
function VocationList_mt:DataLength()
    local o = self.view:Offset(4)
    if o ~= 0 then
        return self.view:VectorLen(o)
    end
    return 0
end
function VocationList.Start(builder) builder:StartObject(1) end
function VocationList.AddData(builder, data) builder:PrependUOffsetTRelativeSlot(0, data, 0) end
function VocationList.StartDataVector(builder, numElems) return builder:StartVector(4, numElems, 4) end
function VocationList.End(builder) return builder:EndObject() end

return VocationList -- return the module