// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cs_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DrunkFish {

  /// <summary>Holder for reflection information generated from cs_data.proto</summary>
  public static partial class CsDataReflection {

    #region Descriptor
    /// <summary>File descriptor for cs_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CsDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1jc19kYXRhLnByb3RvEglEcnVua0Zpc2gicAoIUm9sZURhdGESEgoKVGVt",
            "cGxhdGVJZBgBIAEoBRINCgVMZXZlbBgCIAEoBRIQCghXZWFwb25JZBgDIAEo",
            "BRIOCgZBdHRyaWIYBCADKAUSDgoGU2tpbGxzGAUgAygFEg8KB0J1ZmZlcnMY",
            "BiADKAUiSgoSTW9uc3RlclJlZnJlc2hEYXRhEhcKD01vbnN0ZXJJZGVudGl0",
            "eRgBIAEoBRIbChNMYXN0S2lsbGVkVGltZVN0YW1wGAIgASgFIrYCCg5QbGF5",
            "ZXJJbml0RGF0YRIRCglBY2NvdW50SWQYASABKAMSEwoLUGxheWVySW5kZXgY",
            "AiABKAUSEQoJUm9sZUluZGV4GAMgASgFEhMKC1BsYXllckxldmVsGAQgASgF",
            "EiUKCFJvbGVEYXRhGAUgAygLMhMuRHJ1bmtGaXNoLlJvbGVEYXRhEg8KB1Rh",
            "c2tEaWMYBiADKAUSDgoGQUlMaXN0GAcgAygFEg4KBkNhbXBJZBgIIAEoBRIe",
            "ChZMYXN0Q29udGFjdFJlY29yZFBvaW50GAkgASgFEh0KFVVubG9ja1JlY29y",
            "ZFBvaW50TGlzdBgKIAMoBRI9ChZNb25zdGVyUmVmcmVzaERhdGFMaXN0GAsg",
            "AygLMh0uRHJ1bmtGaXNoLk1vbnN0ZXJSZWZyZXNoRGF0YSK0AQoTQmF0dGxl",
            "V29ybGRJbml0RGF0YRIPCgdMb2dpY0lkGAEgASgEEhUKDUZyYW1lRHVyYXRp",
            "b24YAiABKAUSDwoHTGV2ZWxJZBgDIAEoBRIYChBMb2NhbFBsYXllckluZGV4",
            "GAQgASgFEhcKD1NlcnZlclRpbWVTdGFtcBgFIAEoBRIxCg5QbGF5ZXJJbml0",
            "RGF0YRgGIAMoCzIZLkRydW5rRmlzaC5QbGF5ZXJJbml0RGF0YWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DrunkFish.RoleData), global::DrunkFish.RoleData.Parser, new[]{ "TemplateId", "Level", "WeaponId", "Attrib", "Skills", "Buffers" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DrunkFish.MonsterRefreshData), global::DrunkFish.MonsterRefreshData.Parser, new[]{ "MonsterIdentity", "LastKilledTimeStamp" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DrunkFish.PlayerInitData), global::DrunkFish.PlayerInitData.Parser, new[]{ "AccountId", "PlayerIndex", "RoleIndex", "PlayerLevel", "RoleData", "TaskDic", "AIList", "CampId", "LastContactRecordPoint", "UnlockRecordPointList", "MonsterRefreshDataList" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DrunkFish.BattleWorldInitData), global::DrunkFish.BattleWorldInitData.Parser, new[]{ "LogicId", "FrameDuration", "LevelId", "LocalPlayerIndex", "ServerTimeStamp", "PlayerInitData" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RoleData : pb::IMessage<RoleData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RoleData> _parser = new pb::MessageParser<RoleData>(() => new RoleData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RoleData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DrunkFish.CsDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoleData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoleData(RoleData other) : this() {
      templateId_ = other.templateId_;
      level_ = other.level_;
      weaponId_ = other.weaponId_;
      attrib_ = other.attrib_.Clone();
      skills_ = other.skills_.Clone();
      buffers_ = other.buffers_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RoleData Clone() {
      return new RoleData(this);
    }

    /// <summary>Field number for the "TemplateId" field.</summary>
    public const int TemplateIdFieldNumber = 1;
    private int templateId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TemplateId {
      get { return templateId_; }
      set {
        templateId_ = value;
      }
    }

    /// <summary>Field number for the "Level" field.</summary>
    public const int LevelFieldNumber = 2;
    private int level_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    /// <summary>Field number for the "WeaponId" field.</summary>
    public const int WeaponIdFieldNumber = 3;
    private int weaponId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int WeaponId {
      get { return weaponId_; }
      set {
        weaponId_ = value;
      }
    }

    /// <summary>Field number for the "Attrib" field.</summary>
    public const int AttribFieldNumber = 4;
    private static readonly pb::FieldCodec<int> _repeated_attrib_codec
        = pb::FieldCodec.ForInt32(34);
    private readonly pbc::RepeatedField<int> attrib_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> Attrib {
      get { return attrib_; }
    }

    /// <summary>Field number for the "Skills" field.</summary>
    public const int SkillsFieldNumber = 5;
    private static readonly pb::FieldCodec<int> _repeated_skills_codec
        = pb::FieldCodec.ForInt32(42);
    private readonly pbc::RepeatedField<int> skills_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> Skills {
      get { return skills_; }
    }

    /// <summary>Field number for the "Buffers" field.</summary>
    public const int BuffersFieldNumber = 6;
    private static readonly pb::FieldCodec<int> _repeated_buffers_codec
        = pb::FieldCodec.ForInt32(50);
    private readonly pbc::RepeatedField<int> buffers_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> Buffers {
      get { return buffers_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RoleData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RoleData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TemplateId != other.TemplateId) return false;
      if (Level != other.Level) return false;
      if (WeaponId != other.WeaponId) return false;
      if(!attrib_.Equals(other.attrib_)) return false;
      if(!skills_.Equals(other.skills_)) return false;
      if(!buffers_.Equals(other.buffers_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TemplateId != 0) hash ^= TemplateId.GetHashCode();
      if (Level != 0) hash ^= Level.GetHashCode();
      if (WeaponId != 0) hash ^= WeaponId.GetHashCode();
      hash ^= attrib_.GetHashCode();
      hash ^= skills_.GetHashCode();
      hash ^= buffers_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TemplateId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TemplateId);
      }
      if (Level != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Level);
      }
      if (WeaponId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(WeaponId);
      }
      attrib_.WriteTo(output, _repeated_attrib_codec);
      skills_.WriteTo(output, _repeated_skills_codec);
      buffers_.WriteTo(output, _repeated_buffers_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TemplateId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TemplateId);
      }
      if (Level != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Level);
      }
      if (WeaponId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(WeaponId);
      }
      attrib_.WriteTo(ref output, _repeated_attrib_codec);
      skills_.WriteTo(ref output, _repeated_skills_codec);
      buffers_.WriteTo(ref output, _repeated_buffers_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TemplateId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TemplateId);
      }
      if (Level != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
      }
      if (WeaponId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(WeaponId);
      }
      size += attrib_.CalculateSize(_repeated_attrib_codec);
      size += skills_.CalculateSize(_repeated_skills_codec);
      size += buffers_.CalculateSize(_repeated_buffers_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RoleData other) {
      if (other == null) {
        return;
      }
      if (other.TemplateId != 0) {
        TemplateId = other.TemplateId;
      }
      if (other.Level != 0) {
        Level = other.Level;
      }
      if (other.WeaponId != 0) {
        WeaponId = other.WeaponId;
      }
      attrib_.Add(other.attrib_);
      skills_.Add(other.skills_);
      buffers_.Add(other.buffers_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TemplateId = input.ReadInt32();
            break;
          }
          case 16: {
            Level = input.ReadInt32();
            break;
          }
          case 24: {
            WeaponId = input.ReadInt32();
            break;
          }
          case 34:
          case 32: {
            attrib_.AddEntriesFrom(input, _repeated_attrib_codec);
            break;
          }
          case 42:
          case 40: {
            skills_.AddEntriesFrom(input, _repeated_skills_codec);
            break;
          }
          case 50:
          case 48: {
            buffers_.AddEntriesFrom(input, _repeated_buffers_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TemplateId = input.ReadInt32();
            break;
          }
          case 16: {
            Level = input.ReadInt32();
            break;
          }
          case 24: {
            WeaponId = input.ReadInt32();
            break;
          }
          case 34:
          case 32: {
            attrib_.AddEntriesFrom(ref input, _repeated_attrib_codec);
            break;
          }
          case 42:
          case 40: {
            skills_.AddEntriesFrom(ref input, _repeated_skills_codec);
            break;
          }
          case 50:
          case 48: {
            buffers_.AddEntriesFrom(ref input, _repeated_buffers_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class MonsterRefreshData : pb::IMessage<MonsterRefreshData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MonsterRefreshData> _parser = new pb::MessageParser<MonsterRefreshData>(() => new MonsterRefreshData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MonsterRefreshData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DrunkFish.CsDataReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MonsterRefreshData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MonsterRefreshData(MonsterRefreshData other) : this() {
      monsterIdentity_ = other.monsterIdentity_;
      lastKilledTimeStamp_ = other.lastKilledTimeStamp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MonsterRefreshData Clone() {
      return new MonsterRefreshData(this);
    }

    /// <summary>Field number for the "MonsterIdentity" field.</summary>
    public const int MonsterIdentityFieldNumber = 1;
    private int monsterIdentity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MonsterIdentity {
      get { return monsterIdentity_; }
      set {
        monsterIdentity_ = value;
      }
    }

    /// <summary>Field number for the "LastKilledTimeStamp" field.</summary>
    public const int LastKilledTimeStampFieldNumber = 2;
    private int lastKilledTimeStamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int LastKilledTimeStamp {
      get { return lastKilledTimeStamp_; }
      set {
        lastKilledTimeStamp_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MonsterRefreshData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MonsterRefreshData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MonsterIdentity != other.MonsterIdentity) return false;
      if (LastKilledTimeStamp != other.LastKilledTimeStamp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MonsterIdentity != 0) hash ^= MonsterIdentity.GetHashCode();
      if (LastKilledTimeStamp != 0) hash ^= LastKilledTimeStamp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MonsterIdentity != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MonsterIdentity);
      }
      if (LastKilledTimeStamp != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(LastKilledTimeStamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MonsterIdentity != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MonsterIdentity);
      }
      if (LastKilledTimeStamp != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(LastKilledTimeStamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MonsterIdentity != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MonsterIdentity);
      }
      if (LastKilledTimeStamp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LastKilledTimeStamp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MonsterRefreshData other) {
      if (other == null) {
        return;
      }
      if (other.MonsterIdentity != 0) {
        MonsterIdentity = other.MonsterIdentity;
      }
      if (other.LastKilledTimeStamp != 0) {
        LastKilledTimeStamp = other.LastKilledTimeStamp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MonsterIdentity = input.ReadInt32();
            break;
          }
          case 16: {
            LastKilledTimeStamp = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MonsterIdentity = input.ReadInt32();
            break;
          }
          case 16: {
            LastKilledTimeStamp = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class PlayerInitData : pb::IMessage<PlayerInitData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerInitData> _parser = new pb::MessageParser<PlayerInitData>(() => new PlayerInitData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayerInitData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DrunkFish.CsDataReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerInitData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerInitData(PlayerInitData other) : this() {
      accountId_ = other.accountId_;
      playerIndex_ = other.playerIndex_;
      roleIndex_ = other.roleIndex_;
      playerLevel_ = other.playerLevel_;
      roleData_ = other.roleData_.Clone();
      taskDic_ = other.taskDic_.Clone();
      aIList_ = other.aIList_.Clone();
      campId_ = other.campId_;
      lastContactRecordPoint_ = other.lastContactRecordPoint_;
      unlockRecordPointList_ = other.unlockRecordPointList_.Clone();
      monsterRefreshDataList_ = other.monsterRefreshDataList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerInitData Clone() {
      return new PlayerInitData(this);
    }

    /// <summary>Field number for the "AccountId" field.</summary>
    public const int AccountIdFieldNumber = 1;
    private long accountId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long AccountId {
      get { return accountId_; }
      set {
        accountId_ = value;
      }
    }

    /// <summary>Field number for the "PlayerIndex" field.</summary>
    public const int PlayerIndexFieldNumber = 2;
    private int playerIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PlayerIndex {
      get { return playerIndex_; }
      set {
        playerIndex_ = value;
      }
    }

    /// <summary>Field number for the "RoleIndex" field.</summary>
    public const int RoleIndexFieldNumber = 3;
    private int roleIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RoleIndex {
      get { return roleIndex_; }
      set {
        roleIndex_ = value;
      }
    }

    /// <summary>Field number for the "PlayerLevel" field.</summary>
    public const int PlayerLevelFieldNumber = 4;
    private int playerLevel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PlayerLevel {
      get { return playerLevel_; }
      set {
        playerLevel_ = value;
      }
    }

    /// <summary>Field number for the "RoleData" field.</summary>
    public const int RoleDataFieldNumber = 5;
    private static readonly pb::FieldCodec<global::DrunkFish.RoleData> _repeated_roleData_codec
        = pb::FieldCodec.ForMessage(42, global::DrunkFish.RoleData.Parser);
    private readonly pbc::RepeatedField<global::DrunkFish.RoleData> roleData_ = new pbc::RepeatedField<global::DrunkFish.RoleData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::DrunkFish.RoleData> RoleData {
      get { return roleData_; }
    }

    /// <summary>Field number for the "TaskDic" field.</summary>
    public const int TaskDicFieldNumber = 6;
    private static readonly pb::FieldCodec<int> _repeated_taskDic_codec
        = pb::FieldCodec.ForInt32(50);
    private readonly pbc::RepeatedField<int> taskDic_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> TaskDic {
      get { return taskDic_; }
    }

    /// <summary>Field number for the "AIList" field.</summary>
    public const int AIListFieldNumber = 7;
    private static readonly pb::FieldCodec<int> _repeated_aIList_codec
        = pb::FieldCodec.ForInt32(58);
    private readonly pbc::RepeatedField<int> aIList_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> AIList {
      get { return aIList_; }
    }

    /// <summary>Field number for the "CampId" field.</summary>
    public const int CampIdFieldNumber = 8;
    private int campId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CampId {
      get { return campId_; }
      set {
        campId_ = value;
      }
    }

    /// <summary>Field number for the "LastContactRecordPoint" field.</summary>
    public const int LastContactRecordPointFieldNumber = 9;
    private int lastContactRecordPoint_;
    /// <summary>
    /// 当前关卡最后一次接触的记录点
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int LastContactRecordPoint {
      get { return lastContactRecordPoint_; }
      set {
        lastContactRecordPoint_ = value;
      }
    }

    /// <summary>Field number for the "UnlockRecordPointList" field.</summary>
    public const int UnlockRecordPointListFieldNumber = 10;
    private static readonly pb::FieldCodec<int> _repeated_unlockRecordPointList_codec
        = pb::FieldCodec.ForInt32(82);
    private readonly pbc::RepeatedField<int> unlockRecordPointList_ = new pbc::RepeatedField<int>();
    /// <summary>
    /// 当前关卡已经解锁的记录点列表 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> UnlockRecordPointList {
      get { return unlockRecordPointList_; }
    }

    /// <summary>Field number for the "MonsterRefreshDataList" field.</summary>
    public const int MonsterRefreshDataListFieldNumber = 11;
    private static readonly pb::FieldCodec<global::DrunkFish.MonsterRefreshData> _repeated_monsterRefreshDataList_codec
        = pb::FieldCodec.ForMessage(90, global::DrunkFish.MonsterRefreshData.Parser);
    private readonly pbc::RepeatedField<global::DrunkFish.MonsterRefreshData> monsterRefreshDataList_ = new pbc::RepeatedField<global::DrunkFish.MonsterRefreshData>();
    /// <summary>
    /// 当前关卡的怪物刷新数据
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::DrunkFish.MonsterRefreshData> MonsterRefreshDataList {
      get { return monsterRefreshDataList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayerInitData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayerInitData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AccountId != other.AccountId) return false;
      if (PlayerIndex != other.PlayerIndex) return false;
      if (RoleIndex != other.RoleIndex) return false;
      if (PlayerLevel != other.PlayerLevel) return false;
      if(!roleData_.Equals(other.roleData_)) return false;
      if(!taskDic_.Equals(other.taskDic_)) return false;
      if(!aIList_.Equals(other.aIList_)) return false;
      if (CampId != other.CampId) return false;
      if (LastContactRecordPoint != other.LastContactRecordPoint) return false;
      if(!unlockRecordPointList_.Equals(other.unlockRecordPointList_)) return false;
      if(!monsterRefreshDataList_.Equals(other.monsterRefreshDataList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AccountId != 0L) hash ^= AccountId.GetHashCode();
      if (PlayerIndex != 0) hash ^= PlayerIndex.GetHashCode();
      if (RoleIndex != 0) hash ^= RoleIndex.GetHashCode();
      if (PlayerLevel != 0) hash ^= PlayerLevel.GetHashCode();
      hash ^= roleData_.GetHashCode();
      hash ^= taskDic_.GetHashCode();
      hash ^= aIList_.GetHashCode();
      if (CampId != 0) hash ^= CampId.GetHashCode();
      if (LastContactRecordPoint != 0) hash ^= LastContactRecordPoint.GetHashCode();
      hash ^= unlockRecordPointList_.GetHashCode();
      hash ^= monsterRefreshDataList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AccountId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(AccountId);
      }
      if (PlayerIndex != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PlayerIndex);
      }
      if (RoleIndex != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(RoleIndex);
      }
      if (PlayerLevel != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(PlayerLevel);
      }
      roleData_.WriteTo(output, _repeated_roleData_codec);
      taskDic_.WriteTo(output, _repeated_taskDic_codec);
      aIList_.WriteTo(output, _repeated_aIList_codec);
      if (CampId != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(CampId);
      }
      if (LastContactRecordPoint != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(LastContactRecordPoint);
      }
      unlockRecordPointList_.WriteTo(output, _repeated_unlockRecordPointList_codec);
      monsterRefreshDataList_.WriteTo(output, _repeated_monsterRefreshDataList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AccountId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(AccountId);
      }
      if (PlayerIndex != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PlayerIndex);
      }
      if (RoleIndex != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(RoleIndex);
      }
      if (PlayerLevel != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(PlayerLevel);
      }
      roleData_.WriteTo(ref output, _repeated_roleData_codec);
      taskDic_.WriteTo(ref output, _repeated_taskDic_codec);
      aIList_.WriteTo(ref output, _repeated_aIList_codec);
      if (CampId != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(CampId);
      }
      if (LastContactRecordPoint != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(LastContactRecordPoint);
      }
      unlockRecordPointList_.WriteTo(ref output, _repeated_unlockRecordPointList_codec);
      monsterRefreshDataList_.WriteTo(ref output, _repeated_monsterRefreshDataList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AccountId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(AccountId);
      }
      if (PlayerIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerIndex);
      }
      if (RoleIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RoleIndex);
      }
      if (PlayerLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayerLevel);
      }
      size += roleData_.CalculateSize(_repeated_roleData_codec);
      size += taskDic_.CalculateSize(_repeated_taskDic_codec);
      size += aIList_.CalculateSize(_repeated_aIList_codec);
      if (CampId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CampId);
      }
      if (LastContactRecordPoint != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LastContactRecordPoint);
      }
      size += unlockRecordPointList_.CalculateSize(_repeated_unlockRecordPointList_codec);
      size += monsterRefreshDataList_.CalculateSize(_repeated_monsterRefreshDataList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayerInitData other) {
      if (other == null) {
        return;
      }
      if (other.AccountId != 0L) {
        AccountId = other.AccountId;
      }
      if (other.PlayerIndex != 0) {
        PlayerIndex = other.PlayerIndex;
      }
      if (other.RoleIndex != 0) {
        RoleIndex = other.RoleIndex;
      }
      if (other.PlayerLevel != 0) {
        PlayerLevel = other.PlayerLevel;
      }
      roleData_.Add(other.roleData_);
      taskDic_.Add(other.taskDic_);
      aIList_.Add(other.aIList_);
      if (other.CampId != 0) {
        CampId = other.CampId;
      }
      if (other.LastContactRecordPoint != 0) {
        LastContactRecordPoint = other.LastContactRecordPoint;
      }
      unlockRecordPointList_.Add(other.unlockRecordPointList_);
      monsterRefreshDataList_.Add(other.monsterRefreshDataList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AccountId = input.ReadInt64();
            break;
          }
          case 16: {
            PlayerIndex = input.ReadInt32();
            break;
          }
          case 24: {
            RoleIndex = input.ReadInt32();
            break;
          }
          case 32: {
            PlayerLevel = input.ReadInt32();
            break;
          }
          case 42: {
            roleData_.AddEntriesFrom(input, _repeated_roleData_codec);
            break;
          }
          case 50:
          case 48: {
            taskDic_.AddEntriesFrom(input, _repeated_taskDic_codec);
            break;
          }
          case 58:
          case 56: {
            aIList_.AddEntriesFrom(input, _repeated_aIList_codec);
            break;
          }
          case 64: {
            CampId = input.ReadInt32();
            break;
          }
          case 72: {
            LastContactRecordPoint = input.ReadInt32();
            break;
          }
          case 82:
          case 80: {
            unlockRecordPointList_.AddEntriesFrom(input, _repeated_unlockRecordPointList_codec);
            break;
          }
          case 90: {
            monsterRefreshDataList_.AddEntriesFrom(input, _repeated_monsterRefreshDataList_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            AccountId = input.ReadInt64();
            break;
          }
          case 16: {
            PlayerIndex = input.ReadInt32();
            break;
          }
          case 24: {
            RoleIndex = input.ReadInt32();
            break;
          }
          case 32: {
            PlayerLevel = input.ReadInt32();
            break;
          }
          case 42: {
            roleData_.AddEntriesFrom(ref input, _repeated_roleData_codec);
            break;
          }
          case 50:
          case 48: {
            taskDic_.AddEntriesFrom(ref input, _repeated_taskDic_codec);
            break;
          }
          case 58:
          case 56: {
            aIList_.AddEntriesFrom(ref input, _repeated_aIList_codec);
            break;
          }
          case 64: {
            CampId = input.ReadInt32();
            break;
          }
          case 72: {
            LastContactRecordPoint = input.ReadInt32();
            break;
          }
          case 82:
          case 80: {
            unlockRecordPointList_.AddEntriesFrom(ref input, _repeated_unlockRecordPointList_codec);
            break;
          }
          case 90: {
            monsterRefreshDataList_.AddEntriesFrom(ref input, _repeated_monsterRefreshDataList_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class BattleWorldInitData : pb::IMessage<BattleWorldInitData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BattleWorldInitData> _parser = new pb::MessageParser<BattleWorldInitData>(() => new BattleWorldInitData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BattleWorldInitData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DrunkFish.CsDataReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BattleWorldInitData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BattleWorldInitData(BattleWorldInitData other) : this() {
      logicId_ = other.logicId_;
      frameDuration_ = other.frameDuration_;
      levelId_ = other.levelId_;
      localPlayerIndex_ = other.localPlayerIndex_;
      serverTimeStamp_ = other.serverTimeStamp_;
      playerInitData_ = other.playerInitData_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BattleWorldInitData Clone() {
      return new BattleWorldInitData(this);
    }

    /// <summary>Field number for the "LogicId" field.</summary>
    public const int LogicIdFieldNumber = 1;
    private ulong logicId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong LogicId {
      get { return logicId_; }
      set {
        logicId_ = value;
      }
    }

    /// <summary>Field number for the "FrameDuration" field.</summary>
    public const int FrameDurationFieldNumber = 2;
    private int frameDuration_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FrameDuration {
      get { return frameDuration_; }
      set {
        frameDuration_ = value;
      }
    }

    /// <summary>Field number for the "LevelId" field.</summary>
    public const int LevelIdFieldNumber = 3;
    private int levelId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int LevelId {
      get { return levelId_; }
      set {
        levelId_ = value;
      }
    }

    /// <summary>Field number for the "LocalPlayerIndex" field.</summary>
    public const int LocalPlayerIndexFieldNumber = 4;
    private int localPlayerIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int LocalPlayerIndex {
      get { return localPlayerIndex_; }
      set {
        localPlayerIndex_ = value;
      }
    }

    /// <summary>Field number for the "ServerTimeStamp" field.</summary>
    public const int ServerTimeStampFieldNumber = 5;
    private int serverTimeStamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ServerTimeStamp {
      get { return serverTimeStamp_; }
      set {
        serverTimeStamp_ = value;
      }
    }

    /// <summary>Field number for the "PlayerInitData" field.</summary>
    public const int PlayerInitDataFieldNumber = 6;
    private static readonly pb::FieldCodec<global::DrunkFish.PlayerInitData> _repeated_playerInitData_codec
        = pb::FieldCodec.ForMessage(50, global::DrunkFish.PlayerInitData.Parser);
    private readonly pbc::RepeatedField<global::DrunkFish.PlayerInitData> playerInitData_ = new pbc::RepeatedField<global::DrunkFish.PlayerInitData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::DrunkFish.PlayerInitData> PlayerInitData {
      get { return playerInitData_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BattleWorldInitData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BattleWorldInitData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LogicId != other.LogicId) return false;
      if (FrameDuration != other.FrameDuration) return false;
      if (LevelId != other.LevelId) return false;
      if (LocalPlayerIndex != other.LocalPlayerIndex) return false;
      if (ServerTimeStamp != other.ServerTimeStamp) return false;
      if(!playerInitData_.Equals(other.playerInitData_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (LogicId != 0UL) hash ^= LogicId.GetHashCode();
      if (FrameDuration != 0) hash ^= FrameDuration.GetHashCode();
      if (LevelId != 0) hash ^= LevelId.GetHashCode();
      if (LocalPlayerIndex != 0) hash ^= LocalPlayerIndex.GetHashCode();
      if (ServerTimeStamp != 0) hash ^= ServerTimeStamp.GetHashCode();
      hash ^= playerInitData_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (LogicId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(LogicId);
      }
      if (FrameDuration != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(FrameDuration);
      }
      if (LevelId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(LevelId);
      }
      if (LocalPlayerIndex != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(LocalPlayerIndex);
      }
      if (ServerTimeStamp != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(ServerTimeStamp);
      }
      playerInitData_.WriteTo(output, _repeated_playerInitData_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (LogicId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(LogicId);
      }
      if (FrameDuration != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(FrameDuration);
      }
      if (LevelId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(LevelId);
      }
      if (LocalPlayerIndex != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(LocalPlayerIndex);
      }
      if (ServerTimeStamp != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(ServerTimeStamp);
      }
      playerInitData_.WriteTo(ref output, _repeated_playerInitData_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (LogicId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(LogicId);
      }
      if (FrameDuration != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FrameDuration);
      }
      if (LevelId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LevelId);
      }
      if (LocalPlayerIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LocalPlayerIndex);
      }
      if (ServerTimeStamp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ServerTimeStamp);
      }
      size += playerInitData_.CalculateSize(_repeated_playerInitData_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BattleWorldInitData other) {
      if (other == null) {
        return;
      }
      if (other.LogicId != 0UL) {
        LogicId = other.LogicId;
      }
      if (other.FrameDuration != 0) {
        FrameDuration = other.FrameDuration;
      }
      if (other.LevelId != 0) {
        LevelId = other.LevelId;
      }
      if (other.LocalPlayerIndex != 0) {
        LocalPlayerIndex = other.LocalPlayerIndex;
      }
      if (other.ServerTimeStamp != 0) {
        ServerTimeStamp = other.ServerTimeStamp;
      }
      playerInitData_.Add(other.playerInitData_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            LogicId = input.ReadUInt64();
            break;
          }
          case 16: {
            FrameDuration = input.ReadInt32();
            break;
          }
          case 24: {
            LevelId = input.ReadInt32();
            break;
          }
          case 32: {
            LocalPlayerIndex = input.ReadInt32();
            break;
          }
          case 40: {
            ServerTimeStamp = input.ReadInt32();
            break;
          }
          case 50: {
            playerInitData_.AddEntriesFrom(input, _repeated_playerInitData_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            LogicId = input.ReadUInt64();
            break;
          }
          case 16: {
            FrameDuration = input.ReadInt32();
            break;
          }
          case 24: {
            LevelId = input.ReadInt32();
            break;
          }
          case 32: {
            LocalPlayerIndex = input.ReadInt32();
            break;
          }
          case 40: {
            ServerTimeStamp = input.ReadInt32();
            break;
          }
          case 50: {
            playerInitData_.AddEntriesFrom(ref input, _repeated_playerInitData_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
