// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GameConfig
{

using global::System;
using global::FlatBuffers;

public struct GameConfig : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GameConfig GetRootAsGameConfig(ByteBuffer _bb) { return GetRootAsGameConfig(_bb, new GameConfig()); }
  public static GameConfig GetRootAsGameConfig(ByteBuffer _bb, GameConfig obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GameConfig __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint GlobalConfigParam { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint GlobalConfigParamB(int j) { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(__p.__vector(o) + j * 4) : (uint)0; }
  public int GlobalConfigParamBLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetGlobalConfigParamBBytes() { return __p.__vector_as_span(8); }
#else
  public ArraySegment<byte>? GetGlobalConfigParamBBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public uint[] GetGlobalConfigParamBArray() { return __p.__vector_as_array<uint>(8); }
  public uint GlobalConfigParamCK(int j) { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUint(__p.__vector(o) + j * 4) : (uint)0; }
  public int GlobalConfigParamCKLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetGlobalConfigParamCKBytes() { return __p.__vector_as_span(10); }
#else
  public ArraySegment<byte>? GetGlobalConfigParamCKBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public uint[] GetGlobalConfigParamCKArray() { return __p.__vector_as_array<uint>(10); }
  public uint GlobalConfigParamCV(int j) { int o = __p.__offset(12); return o != 0 ? __p.bb.GetUint(__p.__vector(o) + j * 4) : (uint)0; }
  public int GlobalConfigParamCVLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetGlobalConfigParamCVBytes() { return __p.__vector_as_span(12); }
#else
  public ArraySegment<byte>? GetGlobalConfigParamCVBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public uint[] GetGlobalConfigParamCVArray() { return __p.__vector_as_array<uint>(12); }

  public static Offset<GameConfig> CreateGameConfig(FlatBufferBuilder builder,
      uint id = 0,
      uint GlobalConfigParam = 0,
      VectorOffset GlobalConfigParamBOffset = default(VectorOffset),
      VectorOffset GlobalConfigParamCKOffset = default(VectorOffset),
      VectorOffset GlobalConfigParamCVOffset = default(VectorOffset)) {
    builder.StartObject(5);
    GameConfig.AddGlobalConfigParamCV(builder, GlobalConfigParamCVOffset);
    GameConfig.AddGlobalConfigParamCK(builder, GlobalConfigParamCKOffset);
    GameConfig.AddGlobalConfigParamB(builder, GlobalConfigParamBOffset);
    GameConfig.AddGlobalConfigParam(builder, GlobalConfigParam);
    GameConfig.AddId(builder, id);
    return GameConfig.EndGameConfig(builder);
  }

  public static void StartGameConfig(FlatBufferBuilder builder) { builder.StartObject(5); }
  public static void AddId(FlatBufferBuilder builder, uint id) { builder.AddUint(0, id, 0); }
  public static void AddGlobalConfigParam(FlatBufferBuilder builder, uint GlobalConfigParam) { builder.AddUint(1, GlobalConfigParam, 0); }
  public static void AddGlobalConfigParamB(FlatBufferBuilder builder, VectorOffset GlobalConfigParamBOffset) { builder.AddOffset(2, GlobalConfigParamBOffset.Value, 0); }
  public static VectorOffset CreateGlobalConfigParamBVector(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddUint(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateGlobalConfigParamBVectorBlock(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartGlobalConfigParamBVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddGlobalConfigParamCK(FlatBufferBuilder builder, VectorOffset GlobalConfigParamCKOffset) { builder.AddOffset(3, GlobalConfigParamCKOffset.Value, 0); }
  public static VectorOffset CreateGlobalConfigParamCKVector(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddUint(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateGlobalConfigParamCKVectorBlock(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartGlobalConfigParamCKVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddGlobalConfigParamCV(FlatBufferBuilder builder, VectorOffset GlobalConfigParamCVOffset) { builder.AddOffset(4, GlobalConfigParamCVOffset.Value, 0); }
  public static VectorOffset CreateGlobalConfigParamCVVector(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddUint(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateGlobalConfigParamCVVectorBlock(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartGlobalConfigParamCVVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<GameConfig> EndGameConfig(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GameConfig>(o);
  }
};

public struct GameConfigList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static GameConfigList GetRootAsGameConfigList(ByteBuffer _bb) { return GetRootAsGameConfigList(_bb, new GameConfigList()); }
  public static GameConfigList GetRootAsGameConfigList(ByteBuffer _bb, GameConfigList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public GameConfigList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public GameConfig? Data(int j) { int o = __p.__offset(4); return o != 0 ? (GameConfig?)(new GameConfig()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DataLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<GameConfigList> CreateGameConfigList(FlatBufferBuilder builder,
      VectorOffset dataOffset = default(VectorOffset)) {
    builder.StartObject(1);
    GameConfigList.AddData(builder, dataOffset);
    return GameConfigList.EndGameConfigList(builder);
  }

  public static void StartGameConfigList(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddData(FlatBufferBuilder builder, VectorOffset dataOffset) { builder.AddOffset(0, dataOffset.Value, 0); }
  public static VectorOffset CreateDataVector(FlatBufferBuilder builder, Offset<GameConfig>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, Offset<GameConfig>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<GameConfigList> EndGameConfigList(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<GameConfigList>(o);
  }
};


}
