// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GameConfig
{

using global::System;
using global::FlatBuffers;

public struct UIWindow : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static UIWindow GetRootAsUIWindow(ByteBuffer _bb) { return GetRootAsUIWindow(_bb, new UIWindow()); }
  public static UIWindow GetRootAsUIWindow(ByteBuffer _bb, UIWindow obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public UIWindow __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string UIName { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUINameBytes() { return __p.__vector_as_span(6); }
#else
  public ArraySegment<byte>? GetUINameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetUINameArray() { return __p.__vector_as_array<byte>(6); }
  public string UIGroupName { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUIGroupNameBytes() { return __p.__vector_as_span(8); }
#else
  public ArraySegment<byte>? GetUIGroupNameBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetUIGroupNameArray() { return __p.__vector_as_array<byte>(8); }
  public string AssetPath { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetAssetPathBytes() { return __p.__vector_as_span(10); }
#else
  public ArraySegment<byte>? GetAssetPathBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetAssetPathArray() { return __p.__vector_as_array<byte>(10); }
  public string LuaFile { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLuaFileBytes() { return __p.__vector_as_span(12); }
#else
  public ArraySegment<byte>? GetLuaFileBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetLuaFileArray() { return __p.__vector_as_array<byte>(12); }

  public static Offset<UIWindow> CreateUIWindow(FlatBufferBuilder builder,
      uint Id = 0,
      StringOffset UINameOffset = default(StringOffset),
      StringOffset UIGroupNameOffset = default(StringOffset),
      StringOffset AssetPathOffset = default(StringOffset),
      StringOffset LuaFileOffset = default(StringOffset)) {
    builder.StartObject(5);
    UIWindow.AddLuaFile(builder, LuaFileOffset);
    UIWindow.AddAssetPath(builder, AssetPathOffset);
    UIWindow.AddUIGroupName(builder, UIGroupNameOffset);
    UIWindow.AddUIName(builder, UINameOffset);
    UIWindow.AddId(builder, Id);
    return UIWindow.EndUIWindow(builder);
  }

  public static void StartUIWindow(FlatBufferBuilder builder) { builder.StartObject(5); }
  public static void AddId(FlatBufferBuilder builder, uint Id) { builder.AddUint(0, Id, 0); }
  public static void AddUIName(FlatBufferBuilder builder, StringOffset UINameOffset) { builder.AddOffset(1, UINameOffset.Value, 0); }
  public static void AddUIGroupName(FlatBufferBuilder builder, StringOffset UIGroupNameOffset) { builder.AddOffset(2, UIGroupNameOffset.Value, 0); }
  public static void AddAssetPath(FlatBufferBuilder builder, StringOffset AssetPathOffset) { builder.AddOffset(3, AssetPathOffset.Value, 0); }
  public static void AddLuaFile(FlatBufferBuilder builder, StringOffset LuaFileOffset) { builder.AddOffset(4, LuaFileOffset.Value, 0); }
  public static Offset<UIWindow> EndUIWindow(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<UIWindow>(o);
  }
};

public struct UIWindowList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static UIWindowList GetRootAsUIWindowList(ByteBuffer _bb) { return GetRootAsUIWindowList(_bb, new UIWindowList()); }
  public static UIWindowList GetRootAsUIWindowList(ByteBuffer _bb, UIWindowList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public UIWindowList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public UIWindow? Data(int j) { int o = __p.__offset(4); return o != 0 ? (UIWindow?)(new UIWindow()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DataLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<UIWindowList> CreateUIWindowList(FlatBufferBuilder builder,
      VectorOffset dataOffset = default(VectorOffset)) {
    builder.StartObject(1);
    UIWindowList.AddData(builder, dataOffset);
    return UIWindowList.EndUIWindowList(builder);
  }

  public static void StartUIWindowList(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddData(FlatBufferBuilder builder, VectorOffset dataOffset) { builder.AddOffset(0, dataOffset.Value, 0); }
  public static VectorOffset CreateDataVector(FlatBufferBuilder builder, Offset<UIWindow>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, Offset<UIWindow>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<UIWindowList> EndUIWindowList(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<UIWindowList>(o);
  }
};


}
